In [3]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created :\n",a)

Array created :
 [[1 2 4]
 [5 8 7]]


In [19]:
#creating an array with random value
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.20824404 0.40810933]
 [0.37572382 0.11623599]]


In [6]:
#creating a 3*4 array with all zeros
b=np.zeros((3,4))
print("array with all zeros :\n",b)

array with all zeros :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#create a constant value array
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [2]:
#create sequence of integer from 0 to 30
import numpy as np
e=np.arange(0,30,5)
print(e)


[ 0  5 10 15 20 25]


In [10]:
#reshaping 3*4 array to 2*2*3 array
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("/n Original array:\n",arr)
print("Reshaped array [4,3]:\n",newarr)

/n Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array [4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [11]:
#flatten array
flarr=arr.flatten()
print("\n Original array:\n",arr)
print("\n Flatten array: \n",flarr)


 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Flatten array: 
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [13]:
print("\n No of dimensions:\n",arr.ndim)
print("\n Shape of array:\n",arr.shape)
print("\n Size pf array:\n",arr.size)
print("\nArray type:\n",arr.dtype)
newtype=arr.astype('f')
print("\nConverted array element:\n",newtype)
print("\nConverted array type:\n",newtype.dtype)


 No of dimensions:
 2

 Shape of array:
 (3, 4)

 Size pf array:
 12

Array type:
 int32

Converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]

Converted array type:
 float32


In [14]:
#slicing
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:,3:])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]


In [15]:
c=p.astype('f')
print(c)
e=p.astype('i')
print(e)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
